version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ebank
      MYSQL_USER: ebank
      MYSQL_PASSWORD: ebankpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ebank
      MYSQL_PASSWORD: ebankpass
      MYSQL_DB: ebank
      ADMIN_ID: admin
      ADMIN_PASSWORD: a123
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db_data:
